# ==== Database Config ====
spring.datasource.url=jdbc:mysql://HOST:PORT/DATABASE_NAME?useSSL=false&serverTimezone=UTC
spring.datasource.username=DB_USERNAME
spring.datasource.password=DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==== RabbitMQ Config ====
#rabbitmq.host=RABBITMQ_HOST
#rabbitmq.port=RABBITMQ_PORT
#rabbitmq.username=RABBITMQ_USERNAME
#rabbitmq.password=RABBITMQ_PASSWORD
#rabbitmq.queue=userSubmissionQueue

# Flyway settings
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
#logging.level.org.flywaydb=DEBUG

spring.mail.host=SMTP_HOST
spring.mail.port=SMTP_PORT
spring.mail.username=SMTP_USERNAME
spring.mail.password=SMTP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

admin.notification.email=ADMIN_EMAIL_ADDRESS
admin.notification.email.title=Action Required: ITR Callback Request

# Rate Limiter configuration
resilience4j.ratelimiter.instances.leadServiceRateLimiter.limit-for-period=5
resilience4j.ratelimiter.instances.leadServiceRateLimiter.limit-refresh-period=1m
resilience4j.ratelimiter.instances.leadServiceRateLimiter.timeout-duration=0